version: '3.8'

services:
  sandesh-todo-front-dev:
    image: sandesh-todo-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001/
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: sandesh-todo-front-dev
