version: '3.8'

services:
  debug-helper:
    image: busybox

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todoapp-dev
    volumes:
      - ./server/pgdata-dev:/var/lib/postgresql/data-dev
    container_name: sandesh-postgres-dev

  server:
    image: sandesh-todo-backend-dev
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL_DEVELOPMENT=postgres://root:admin@sandesh-postgres-dev:5432/todoapp-dev
      - PORT=3001
      - SECRET_KEY=ZWiIyT4zHeAfpUoj7us5QNWR+UwankdgYHeH+HXoRx98SuLPsTF+nb7Sf5ikdpOo9lBCQ3RG5kIMUm3o/pNHhQ==
      - SALT=12
    container_name: sandesh-todo-server-dev
    depends_on:
      - postgres

  client:
    image: sandesh-todo-front-dev
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    volumes:
      - ./client:/usr/src/app
    ports:
      - 3000:3000
    container_name: sandesh-todo-client-dev
    depends_on:
      - server

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: sandesh-todo-reverse-proxy-dev
    depends_on:
      - client
