GET http://localhost:8080/api/v1/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJuYW1lIjoic2FuZGVzaCIsInVzZXJuYW1lIjoic3VuZGVzekBnbWFpbC5jb20iLCJ1c2VySWQiOiJkODdmYTA1ZS03OWYzLTQ5OTUtOGM1MS1hMjJmNGZjMGZmYmEiLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2NzU0NTU5MjUsImV4cCI6MTY3NTQ1NjgyNX0.s51utOIiOcpk5G_BPJ6Bp2YZr7qIlpqc7vmJb05kSK8

###
POST http://localhost:8080/api/v1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJuYW1lIjoic2FuZGVzaCIsInVzZXJuYW1lIjoic3VuZGVzekBnbWFpbC5jb20iLCJ1c2VySWQiOiJkODdmYTA1ZS03OWYzLTQ5OTUtOGM1MS1hMjJmNGZjMGZmYmEiLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2NzU0NTU5MjUsImV4cCI6MTY3NTQ1NjgyNX0.s51utOIiOcpk5G_BPJ6Bp2YZr7qIlpqc7vmJb05kSK8

{
  "content": "sandesh 1"
}


###
PUT http://localhost:8080/api/v1/tasks/9b3ad0f9-41c9-4739-8ad3-22534fc35e8b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJuYW1lIjoic2FuZGVzaCIsInVzZXJuYW1lIjoic3VuZGVzekBnbWFpbC5jb20iLCJ1c2VySWQiOiJkODdmYTA1ZS03OWYzLTQ5OTUtOGM1MS1hMjJmNGZjMGZmYmEiLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2NzU0NTU5MjUsImV4cCI6MTY3NTQ1NjgyNX0.s51utOIiOcpk5G_BPJ6Bp2YZr7qIlpqc7vmJb05kSK8

{
  "taskId": "50",
  "important": "true",
  "isCompleted": "true"
}


###

DELETE http://localhost:8080/api/v1/tasks/17b36f17-0d9e-47c5-b441-b2c71d4ef80c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJuYW1lIjoic2FuZGVzaCIsInVzZXJuYW1lIjoic3VuZGVzekBnbWFpbC5jb20iLCJ1c2VySWQiOiJkODdmYTA1ZS03OWYzLTQ5OTUtOGM1MS1hMjJmNGZjMGZmYmEiLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2NzU0NTU5MjUsImV4cCI6MTY3NTQ1NjgyNX0.s51utOIiOcpk5G_BPJ6Bp2YZr7qIlpqc7vmJb05kSK8


###
POST http://localhost:8080/api/v1/test/reset