GET http://localhost:3001/api/v1/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FuZGVzaCBIeW9qdSIsInVzZXJuYW1lIjoic3VuZGVzekBnbWFpbC5jb20iLCJpZCI6ImJhNDk4NDExLTMzZjAtNDZhYy1iNTQzLTcyNDE4ZDljN2EwNCIsImlhdCI6MTY0NDk1Mzc4NiwiZXhwIjoxNjQ1MjUzNzg2fQ.Y6FUMB4RWlbcQU6vmXnP9AbDIBuAdwTgOHLRXfHuQTk

###
POST http://localhost:3001/api/v1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FuZGVzaCBIeW9qdSIsInVzZXJuYW1lIjoic3VuZGVzekBnbWFpbC5jb20iLCJpZCI6ImJhNDk4NDExLTMzZjAtNDZhYy1iNTQzLTcyNDE4ZDljN2EwNCIsImlhdCI6MTY0NDk1Mzc4NiwiZXhwIjoxNjQ1MjUzNzg2fQ.Y6FUMB4RWlbcQU6vmXnP9AbDIBuAdwTgOHLRXfHuQTk

{
  "contents": "sandesh 1"
}


###
PUT http://localhost:3001/api/v1/tasks/2aef62a9-3f57-477d-ac16-ce37ab6986ad
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FuZGVzaCBIeW9qdSIsInVzZXJuYW1lIjoic3VuZGVzekBnbWFpbC5jb20iLCJpZCI6ImJhNDk4NDExLTMzZjAtNDZhYy1iNTQzLTcyNDE4ZDljN2EwNCIsImlhdCI6MTY0NDk1Mzc4NiwiZXhwIjoxNjQ1MjUzNzg2fQ.Y6FUMB4RWlbcQU6vmXnP9AbDIBuAdwTgOHLRXfHuQTk

{
  "isCompleted": "true"
}


###

DELETE http://localhost:3001/api/v1/tasks/25fbca09-b263-4831-8b88-ce27e7947dca
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FuZGVzaCBIeW9qdSIsInVzZXJuYW1lIjoic3VuZGVzekBnbWFpbC5jb20iLCJpZCI6ImJhNDk4NDExLTMzZjAtNDZhYy1iNTQzLTcyNDE4ZDljN2EwNCIsImlhdCI6MTY0NDk1Mzc4NiwiZXhwIjoxNjQ1MjUzNzg2fQ.Y6FUMB4RWlbcQU6vmXnP9AbDIBuAdwTgOHLRXfHuQTk


###
POST http://localhost:3001/api/v1/test/reset