version: '3.8'

services:
  postgresdb-todo:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    container_name: pg-todo-test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todoapp-test
    volumes:
      - todo-pgdata-test:/var/lib/postgresql/data

volumes:
  todo-pgdata-test:
