version: '3.8'

services:
  postgresdb-todo:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    container_name: pg-todo-dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todoapp-dev
    volumes:
      - todo-pgdata-dev:/var/lib/postgresql/data

volumes:
  todo-pgdata-dev:
