version: '3.8'

services:
  postgresdb-todo:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    container_name: pg-todo
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todoapp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
